/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BLOCKS_H_RPCGEN
#define _BLOCKS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define BLKS_N_1ST_LO 6
#define BLKS_N_2ND_LO 4
#define BLKS_MAX_VXI_SLOT 12
#define BLKS_MIN_VXI_SLOT 0
#define BLKS_SUCCESS 1
#define BLKS_FAILURE 0
#define BLKS_NO_HARDWARE 1
#define BLKS_BAD_SLOT 2

struct blksStatus {
	int status;
	int reason;
};
typedef struct blksStatus blksStatus;

struct blksConfiguration {
	double lO1Frequency[BLKS_N_1ST_LO];
	int doLO1[BLKS_N_1ST_LO];
	double lO2Frequency[BLKS_N_2ND_LO];
	int doLO2[BLKS_N_2ND_LO];
};
typedef struct blksConfiguration blksConfiguration;

struct blksCommand {
	int command;
};
typedef struct blksCommand blksCommand;

struct blksInfo {
	double lO1Frequency[BLKS_N_1ST_LO];
	double lO2Frequency[BLKS_N_2ND_LO];
};
typedef struct blksInfo blksInfo;

#define BLKSPROG 0x20000102
#define BLKSVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define BLKSREQUEST 1
extern  blksStatus * blksrequest_1(blksConfiguration *, CLIENT *);
extern  blksStatus * blksrequest_1_svc(blksConfiguration *, struct svc_req *);
#define BLKSINQUIRY 2
extern  blksInfo * blksinquiry_1(blksCommand *, CLIENT *);
extern  blksInfo * blksinquiry_1_svc(blksCommand *, struct svc_req *);
extern int blksprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define BLKSREQUEST 1
extern  blksStatus * blksrequest_1();
extern  blksStatus * blksrequest_1_svc();
#define BLKSINQUIRY 2
extern  blksInfo * blksinquiry_1();
extern  blksInfo * blksinquiry_1_svc();
extern int blksprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_blksStatus (XDR *, blksStatus*);
extern  bool_t xdr_blksConfiguration (XDR *, blksConfiguration*);
extern  bool_t xdr_blksCommand (XDR *, blksCommand*);
extern  bool_t xdr_blksInfo (XDR *, blksInfo*);

#else /* K&R C */
extern bool_t xdr_blksStatus ();
extern bool_t xdr_blksConfiguration ();
extern bool_t xdr_blksCommand ();
extern bool_t xdr_blksInfo ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BLOCKS_H_RPCGEN */
