#!/bin/tcsh -vf
while (1)
/application/bin/observe -s irc+10216
sleep 3
tsys
/application/bin/integrate -s 30 -w
/application/bin/observe -s 0854+201
sleep 3
tsys
/application/bin/integrate -s 30 -w
end

