#!/bin/tcsh -vf
while (1)
/application/bin/observe -s bnkl1
sleep 3
tsys
/application/bin/integrate -s 30 -w
/application/bin/observe -s 0423-013
sleep 3
tsys
/application/bin/integrate -s 30 -w
end

