#!/usr/local/bin/perl
# usage: holoSetup a1 a2 a3 
# TK Aug 2013
if( $#ARGV < 0 ) {die "Usage: holoSetupLockIn entry\n"; }
$entry=shift;

VVM1:
$lock1=0;
$lock2=0;
print "\n checking Lock-In lock .... \n \n";
$lock1=1 & (split(' ',`lockinGPIB  10 LIAS\\?0 | grep response:`))[2];
#$lock2=1 & (split(' ',`lockinGPIB  11 LIAS\?0 | grep response:`))[3];
print "lock1 = $lock1; lock 2 = $lock2\n";
if ($lock1 == 1) {print "Lock-In1 in lock \n"} else {print "Lock-In1 not in lock\n"};
if ($lock2 == 1) {print "Lock-In2 in lock \n"} else {print "Lock-In2 not in lock\n"};
if ($lock1 != 0 | $lock2 != 0) {print "not in lock; exiting ...\n"; goto EXIT; };
exit;

EXIT:
exit;
