#!/bin/tcsh
while (1)
tune -a 1 -c vbias0 2.38
tune -a 2 -c vbias0 2.52
tune -a 3 -c vbias0 2.42
tune -a 5 -c vbias0 2.38
tune -a 6 -c vbias0 2.43
tune -a 7 -c 'vbias0 2.45' 
tune -a 8 -c vbias0 2.62
tune -a 1 -c vbias1 2.29
tune -a 2 -c vbias1 2.22
tune -a 3 -c vbias1 2.51
tune -a 5 -c vbias1 2.21
tune -a 6 -c vbias1 2.40
tune -a 7 -c 'vbias1 -4.00'
tune -a 8 -c 'vbias1 1.90'
sleep 1800
tune -c vbias0 10
tune -c vbias1 10
sleep 1800
end

