/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CCD_H_RPCGEN
#define	_CCD_H_RPCGEN

#include <rpc/rpc.h>

struct ccdCommand {
	short acquireFlag;
	short ccdResponse;
};
typedef struct ccdCommand ccdCommand;

struct antenaQuery {
	int antenaNumber;
};
typedef struct antenaQuery antenaQuery;
#define	SUCCESS 1
#define	FAILURE 0

#define	CCDCOMMANDPROG	0x20000202
#define	CCDCOMMANDVERS	1
#define	CCDCOMMAND	1
extern  ccdCommand * ccdcommand_1();
extern int ccdcommandprog_1_freeresult();

/* the xdr functions */
extern bool_t xdr_ccdCommand();
extern bool_t xdr_antenaQuery();

#endif /* !_CCD_H_RPCGEN */
