/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ccd.h"
#ifndef _KERNEL
#include <stdio.h>
#include <stdlib.h> /* getenv, exit */
#endif /* !_KERNEL */

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

ccdCommand *
ccdcommand_1(argp, clnt)
	ccdCommand *argp;
	CLIENT *clnt;
{
	static ccdCommand clnt_res;

	memset((char *)&clnt_res, 0, sizeof (clnt_res));
	if (clnt_call(clnt, CCDCOMMAND,
		(xdrproc_t) xdr_ccdCommand, (caddr_t) argp,
		(xdrproc_t) xdr_ccdCommand, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
