/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ccd.h"

bool_t
xdr_ccdCommand(xdrs, objp)
	register XDR *xdrs;
	ccdCommand *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_short(xdrs, &objp->acquireFlag))
		return (FALSE);
	if (!xdr_short(xdrs, &objp->ccdResponse))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_antenaQuery(xdrs, objp)
	register XDR *xdrs;
	antenaQuery *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_int(xdrs, &objp->antenaNumber))
		return (FALSE);
	return (TRUE);
}
