CC = gcc -I$(GLOBALINC)
BIN = $(HALBIN)/recordTilts
LIBSMAPOPT=../../smapopt/libsmapopt.a
VPATH=$(COMMONINC)

all: $(BIN)

recordTilts.o: recordTilts.c 
	$(CC) -g -Wall -I$(COMMONINC) recordTilts.c -c

$(HALBIN)/recordTilts: recordTilts.o $(COMMONLIB)/rm.o /usr/PowerPC/applications/hal/pointingHeaders/ph.o $(COMMONLIB)/libdsm.a
	$(CC) -g -o $@ $^ $(LIBSMAPOPT) -lrpc -lnetinet -mthreads
