CC = gcc -I$(GLOBALINC)
BIN = $(HALBIN)/recordContinuum
LIBSMAPOPT=../../smapopt/libsmapopt.a

all: $(BIN)

recordContinuum.o: recordContinuum.c $(COMMONLIB)/ph.o
	$(CC) -g -Wall recordContinuum.c -c -I$(COMMONINC)

$(HALBIN)/recordContinuum: recordContinuum.o $(COMMONLIB)/rm.o $(COMMONLIB)/libdsm.a $(COMMONLIB)/ph.o
	$(CC) -g -o $@  recordContinuum.o $(COMMONLIB)/rm.o $(COMMONLIB)/ph.o \
	$(COMMONLIB)/libdsm.a -I$(COMMONINC) $(LIBSMAPOPT) -lrpc -lnetinet -mthreads
