#!/bin/tcsh -vf
/application/bin/observe -s uranus
sleep 5
tsys
/application/bin/integrate -s 30 -w
#
while (1)
/application/bin/observe -s 2202+422
sleep 5
tsys
/application/bin/integrate -s 10 -w
/application/bin/observe -s crl2688 -r 21:02:18.82 -d +36:41:37.5 -e 2000 -v 1.2
sleep 5
tsys
/application/bin/integrate -s 40 -w
end

