#!/bin/tcsh -vf
/application/bin/observe -s 3c345
sleep 5
tsys
/application/bin/integrate -s 10 -w
/application/bin/observe -s X-Her -r 16:02:39.174 -d 47:14:25.28 -v -73.0
sleep 5
/application/bin/integrate -s 60 -w
/application/bin/observe -s 3c345
sleep 5
tsys
/application/bin/integrate -s 10 -w -b

