#!/bin/tcsh -vf
/application/bin/observe -t gain -s 0059+581
sleep 5
tsys
/application/bin/integrate -s 10 -w
/application/bin/observe -t gain -s R-Cas -r 23:58:24.873 -d 51:23:19.70 -v 26.0
sleep 5
/application/bin/integrate -s 60 -w
/application/bin/observe -t gain -s 0059+581
sleep 5
tsys
/application/bin/integrate -s 10 -w -b

