/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STI_H_RPCGEN
#define _STI_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct commandStatus {
	int status;
	char errorMessage[128];
};
typedef struct commandStatus commandStatus;

struct commandRequest {
	double exposureSec;
	char fileNamePrefix[80];
};
typedef struct commandRequest commandRequest;

#define STIPROG 0x20000111
#define STIVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define STICOMMANDREQUEST 0
extern  commandStatus * sticommandrequest_1(commandRequest *, CLIENT *);
extern  commandStatus * sticommandrequest_1_svc(commandRequest *, struct svc_req *);
extern int stiprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define STICOMMANDREQUEST 0
extern  commandStatus * sticommandrequest_1();
extern  commandStatus * sticommandrequest_1_svc();
extern int stiprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_commandStatus (XDR *, commandStatus*);
extern  bool_t xdr_commandRequest (XDR *, commandRequest*);

#else /* K&R C */
extern bool_t xdr_commandStatus ();
extern bool_t xdr_commandRequest ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STI_H_RPCGEN */
