/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "sti.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

commandStatus *
sticommandrequest_1(commandRequest *argp, CLIENT *clnt)
{
	static commandStatus clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, STICOMMANDREQUEST,
		(xdrproc_t) xdr_commandRequest, (caddr_t) argp,
		(xdrproc_t) xdr_commandStatus, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
