/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sti.h"

bool_t
xdr_commandStatus (XDR *xdrs, commandStatus *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->errorMessage, 128,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_commandRequest (XDR *xdrs, commandRequest *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_double (xdrs, &objp->exposureSec))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fileNamePrefix, 80,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
