#!/usr/local/bin/perl
#beacon
#This script commands the antenna(s) to point at the holography beacon.
#It first looks up which pad it is on. - TRH  Jan 2005

@antennalist = ();

sub Usage() {
  print "Usage: beacon_padlookup_690 -a 3\n beacon_padlookup_690 --antenna 3\n";
}
use Getopt::Long;
GetOptions('antenna=i'=>\$antennaNumber);
$lowfreq = 1;  
#find the antennas specified in the project command.
if ($antennaNumber!=0) {
  if (($antennaNumber<1)||($antennaNumber>8)) {
    &Usage;
    die "Antenna number should be 1..8.\n";
  }
  push(@antennalist,$antennaNumber);
} else {
# no antenna was specified, so do them all
  for ($i=1;$i<=8;$i++) {
    $antenna_status=`value -a $i -v antenna_status`;
    if ($antenna_status==1) { 
      push(@antennalist,$i);
    }
  }
}

foreach $antennaNumber (@antennalist) {
  $pad_id = `value -v pad_id -a $antennaNumber`;
  if ($pad_id==1) {
      $az = 48.474; $el = 18.695; $counts = 77379;
  } elsif ($pad_id==4) {
      $az = 53.300; $el = 17.146; $counts = 65500;
  } elsif ($pad_id==5) {
      $az = 55.793; $el =  18.296; $counts = 71100;
  } elsif ($pad_id==7) {
      $az = 48.874; $el = 16.658; $counts = 66232;
  } elsif ($pad_id==8) {
      $az = 54.294; $el = 14.938; $counts = 64224;
  } elsif ($pad_id==9) { 
      $az = 60.130; $el = 15.949; $counts = 60300;
  } elsif ($pad_id==11) { 
      $az = 61.350; $el = 19.844; $counts = 72000;
  } elsif ($pad_id==17) { 
      $az = 49.813; $el = 11.725; $counts = 42732;
  } else {
      printf "Could not find a valid pad ID for antenna %d\n",$antennaNumber;
      exit(0);
  }
  printf "Sending antenna %d to azimuth = %.4f, elev = %.4f\n",$antennaNumber,$az,$el;
  `azel -a $antennaNumber -z $az -e $el`;
  printf "Sending chopper %d to counts = %d\n",$antennaNumber,$counts;
  `positionChopper -c -f -z $counts -a $antennaNumber`;
}
