#!/usr/local/bin/perl
#beacon
#This script commands the antenna(s) to point at the holography beacon.
#It first looks up which pad it is on. - TRH  22 May 2002

@antennalist = ();

sub Usage() {
  print "Usage: beacon_padlookup -a 3\n beacon_padlookup --antenna 3\n";
}
use Getopt::Long;
GetOptions('antenna=i'=>\$antennaNumber);
$lowfreq = 1;  
#find the antennas specified in the project command.
if ($antennaNumber!=0) {
  if (($antennaNumber<1)||($antennaNumber>8)) {
    &Usage;
    die "Antenna number should be 1..8.\n";
  }
  push(@antennalist,$antennaNumber);
} else {
# no antenna was specified, so do them all
  for ($i=1;$i<=8;$i++) {
    $antenna_status=`value -a $i -v antenna_status`;
    if ($antenna_status==1) { 
      push(@antennalist,$i);
    }
  }
}

foreach $antennaNumber (@antennalist) {
  $pad_id = `value -v pad_id -a $antennaNumber`;
  if ($pad_id==1) {
      $az = 48.4278; $el = 18.6846; $counts = 77379;
  } elsif ($pad_id==4) {
      $az = 53.28863; $el = 17.1541; $counts = 65500;
  } elsif ($pad_id==5) {
      $az = 55.7881; $el =  18.3000; $counts = 71100;
  } elsif ($pad_id==7) {
      $az = 48.77; $el = 16.695; $counts = 66232;
  } elsif ($pad_id==8) {
      $az = 54.19; $el = 14.975; $counts = 64224;
  } elsif ($pad_id==9) { 
      $az = 60.032; $el = 15.983; $counts = 60300;
  } elsif ($pad_id==11) { 
      $az = 61.238; $el = 19.883; $counts = 72000;
  } elsif ($pad_id==17) { 
      $az = 49.75; $el = 11.747; $counts = 42732;
  } else {
      printf "Could not find a valid pad ID for antenna %d\n",$antennaNumber;
      exit(0);
  }
  printf "Sending antenna %d to azimuth = %.4f, elev = %.4f\n",$antennaNumber,$az,$el;
  `azel -a $antennaNumber -z $az -e $el`;
  printf "Sending chopper %d to counts = %d\n",$antennaNumber,$counts;
  `positionChopper -c -f -z $counts -a $antennaNumber`;
}
