#!/usr/bin/perl
# converts a space-delimited list into a comma-delimited list. - Todd Hunter
# used by "azelstar"
@args = split(' ',$ARGV[0]);
for ($i=0; $i<=$#args; $i++) {
    if ($args[$i] =~ /-h/) {
	print "Usage: $0 <space-delimited list>\n";
	print "  it will output a comma-delimited list, which is useful in scripts\n"; 
	exit;
    }
    print "$args[$i]";
    if ($i<$#args) {
	print ",";
    }
}
print "\n";
#
