#!/usr/bin/perl

$hourlimit = 8;
$obsFrequency = 0; 
$obsFrequencyHigh = 684.0;

sub Usage() {
    print "This script will command the antennas to do a modified skydip (only low elev)\n";
    print "  The -f flag is optional. If given, the argument should be the LO frequency\n";
    print "  If it is not given (this is preferred), then value will read from DSM.\n";
    print "Usage: dip [-a 4] [-f 237.4] [-g 658.0] -c<optional> [-e <firstElev>]\n dip [--antenna 4] [--frequency 237.4] --syncdet --coldload<optional>\n  if -a is not given, all antennas in the project command will be dipped simultaneously\n";
    print "  The -g flag is optional. If given, the argument should be the high-frequency\n    receiver's LO frequency.  Otherwise, it will be read from DSM.\n";
    print "More than one antenna can be specified,  for example, -a 3..5,8\n";
    print "By default, data will be read from syncdet2_channels_v2.\n";
    print "The coldload dataline will be written if the timestamp is recent enough\n";
    print "   ($hourlimit hours).  Use the -c argument to force it to be written.\n";
}
 
foreach $i ( @ARGV ) {
    $args = $args . $i . " ";
}

use  POSIX;
use Getopt::Long;
use FileHandle;
$pid=POSIX::getpid();
$Getopt::Long::autoabbrev=1;
$antennaPick = 0;
#
# read obsFrequency from DSM
# old way:
#$obsFrequency = `readDSM -l -m m5 -v DSM_AS_IFLO_REST_FR_V2_D -i 0`;
#$sideband = `readDSM -l -m m5 -v DSM_AS_IFLO_SIDEBAND_V2_S -i 0`;
#  by Taco's standard, having the line in USB corresponds to sideband==-1
#$obsFrequency += $sideband*5.0;
#
# new way:
$obsFrequency = `readDSM -l -m newdds -v dds_to_hal_x -s FREQ_V3_D -i 1`;
$obsFrequency *= 0.000000001;  # convert to GHz
$opt_syncdet = 1;
$firstElev = 45.0;
#
# read obsFrequencyHigh from DSM
# old way:
# $sidebandHigh = `readDSM -l -m m5 -v DSM_AS_IFLO_SIDEBAND_V2_S -i 1`;
# $obsFrequencyHigh = `readDSM -l -m m5 -v DSM_AS_IFLO_REST_FR_V2_D -i 1`;
# $obsFrequencyHigh += $sidebandHigh*5.0;
#
# new way (more accurate):
$obsFrequencyHigh = `readDSM -l -m newdds -v dds_to_hal_x -s FREQ_V3_D -i 2`;
$obsFrequencyHigh *= 0.000000001;  # convert to GHz
#  by Taco's standard, having the line in USB corresponds to sideband==-1
if ($obsFrequencyHigh != $obsFrequencyHigh || $obsFrequencyHigh < 300
    || $obsFrequencyHigh > 900) {
    $obsFrequencyHigh = 684.0;
}
#
GetOptions('antenna=s'=>\$antennaPick,'frequency=f'=>\$obsFrequency,'gFrequencyHigh=f'=>\$obsFrequencyHigh,'coldload','help','elevation=f'=>\$firstElev,'syncdet');
@antennalist = ();

# always print the cold load value, if the timestamp is recent enough
$opt_coldload = 1;

if ($firstElev > 80 || $firstElev < 20) {
    Usage();
    print "First elev must be between 20 and 80\n";
    exit(0);
} 

if ($obsFrequency<160 or $obsFrequency>900) {
  print "Please specify the LO frequency in GHz using -f \n";
  print "Frequency must be 160 - 900 GHz.\n";
  Usage();
  exit(0);
}

if($opt_help) {
  Usage();
  exit(0);
}


#die "debug\n";
print "antennaPick = $antennaPick\n";
if ($antennaPick != 0) {
  $checklist = `/application/bin/getAntList -a $antennaPick -l`;
  @antennalisttemp = split(' ',$checklist);
  $numants = @antennalisttemp;
  for ($antindex=0; $antindex<$numants; $antindex++) {
    if (($antennalisttemp[$antindex]<1) || ($antennalisttemp[$antindex]>8)) {
      Usage();
      die "Check the command-line arguments.\n";
    }
    push @antennalist, $antennalisttemp[$antindex];
    printf "Will use antenna %d\n",$antennalisttemp[$antindex];
  }
} else {
# no antenna was specified, get the list from the project command
    print "Will use all antennas in the project:\n";
    $antcount = 0;
    for ($i=1; $i<=8; $i++) {
	$antenna_status=`value -a $i -v antenna_status`;
	if ($antenna_status==1) { 
	    push(@antennalist,$i); 
	    print "Will use antenna $i\n";
	    $antcount++;
	}       
    }
    print "@antennalist\n";
    $command = "commaAntennaList -a \"@antennalist\"";
    print $command."\n";
    $antennaPick = `commaAntennaList "@antennalist"`;
    chomp($antennaPick);
}

print "Will use antennas: $antennaPick\n"; 

open(logfile,">>/rootfs/logs/SMAshLog");
$line = `date -u +"%a %b %d %X %Y"`;
chop($line);
$user = $ENV{"USER"};
printf logfile "%s ($user): $0 %s\n", $line, $args;
close(logfile);


@fileHandles = ();

$command="openM3 -a $antennaPick";
print $command."\n";
system($command);
sleep 3;
$command="el -d $firstElev -a $antennaPick"; 
print $command."\n";
system($command);
sleep 3;
$command="resume -a $antennaPick";
print $command."\n";
system($command);
sleep 3;

foreach $antennaNumber (@antennalist) {
# open up data files and send each telescope to starting elevation
  print "Start dip scan Ant $antennaNumber\n";
  ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst)=localtime(time);
  $date_name = sprintf "%02d%02d%02d_%02d%02d",$year-100,$mon+1,$mday,$hour,$min;
  $filename[$antennaNumber] = "/data/engineering/dip_scan/$date_name.dip$antennaNumber";
  print "opening file: $filename[$antennaNumber]\n";
  $fh = new FileHandle $filename[$antennaNumber], O_WRONLY|O_CREAT or die("cannot open the output file $filename[$antennaNumber]\n");
  push @fileHandles, $fh;
}
sleep(5);

# put in the hot load
foreach $antennaNumber (@antennalist) {
  $command="tune -a $antennaNumber -c hotload in";
  system($command);
  flush;
}
sleep(5);


# record the hot voltage and remove the hot load
$index = 0;
foreach $antennaNumber (@antennalist) {
# record hotload voltage, etc. in the file header
  if($opt_syncdet) {
    $powers = `value -a $antennaNumber -v syncdet2_channels_v2`;
    @list = split(' ',$powers);
    $hot = $list[0];
    $hothigh = $list[1];
  } else {
    $hot = `value -a $antennaNumber -v hotload_lowfreq_volts`;
    $hothigh = `value -a $antennaNumber -v hotload_highfreq_volts`;
  }
  chomp($hot);
  $command="tune -a $antennaNumber -c hotload out";
  system($command);
  flush;
  $hot_tmp = 273.15+`value -a $antennaNumber -v ambientload_temperature`;
  $ambient_tmp = 273.15+`value -a $antennaNumber -v weather_temp`;
  if ($opt_coldload) {
    print { $fileHandles[$index] } "# tcold 77.0\n";
    $cold = `value -a $antennaNumber -v coldload_lowfreq_volts`;
    chomp($cold);
    $coldtime = `value -a $antennaNumber -v coldload_lowfreq_volts_timestamp`;
    chomp($coldtime);
    $coldhigh = `value -a $antennaNumber -v coldload_highfreq_volts`;
    chomp($coldhigh);
    $coldhightime = `value -a $antennaNumber -v coldload_highfreq_volts_timestamp`;
    chomp($coldhightime);
    $unixtime = `value -a $antennaNumber -v unix_time`;
    chomp($unixtime);
    print " low-freq rx: cold load = $cold at timestamp = $coldtime, unixtime = $unixtime";
    print "high-freq rx: cold load = $coldhigh at timestamp = $coldhightime, unixtime = $unixtime";
  }
  print { $fileHandles[$index] } "# thot $hot_tmp\n";
  print { $fileHandles[$index] } "# hot $hot $hothigh\n";
  print { $fileHandles[$index] } "# bias 0.0\n";
  print { $fileHandles[$index] } "# tamb $ambient_tmp\n";
  print { $fileHandles[$index] } "# freq $obsFrequency $obsFrequencyHigh\n";
  if ($opt_coldload) {
      $age = $unixtime-$coldtime;
      if ($unixtime > $coldtime) {
	  if (($unixtime-$coldtime) < ($hourlimit*3600)) {
	      print { $fileHandles[$index] } "# cold $cold $coldhigh\n";
	      print { $fileHandles[$index] } "# timestamp $coldtime $coldhightime\n";
	  } else {
	      print "Not printing cold load values to the file because the timestamp is too old (i.e. more than $hourlimit hours).\n";
	  }
      } else {
	  print "Not printing cold load values to the file because the timestamp appears to be in the future.\n";
      }
  }
  print { $fileHandles[$index] } "# antennaNumber $antennaNumber\n";
  print { $fileHandles[$index] } "# date $date_name\n";
  $index++;
}
sleep(5);

#die "debug\n";
foreach $a (@antennalist) {
  $command="resume -a $a";
  print $command."\n";
  system($command);
  flush;
  flush;
#  $xnpts[$a] = 0;      $sumx[$a] = 0;      $sumy[$a] = 0;
#  $sumy2[$a]= 0;      $sumx2[$a] = 0;      $sumxy[$a] = 0;
}

gotoel($firstElev);
gotoel(30.0);
gotoel(26.0);
gotoel(24.0);
gotoel(22.0);
gotoel(20.0);
gotoel(18.0);
gotoel(16.0);
gotoel(15.0);
gotoel(14.0);

#gotoel(14.48);
#gotoel(12.84);
#gotoel(11.54);
#gotoel(10.48);

print "closing file handles\n";
for ($i=0; $i<=$#antennalist; $i++) {
  close($fileHandles[$i]);
}
foreach $antennaNumber (@antennalist) {
  print "Data left in file = $filename[$antennaNumber]\n";
  `chmod 666 $filename[$antennaNumber]`;
}
print "done!\n";
print "To see the results, go to the monitor 'w' page.\n";

sub gotoel {
  my $el_command=shift(@_);
  print "process ID = $pid ";
  print "$el_command\n";
# send all antennas to the specified elevation
  $command="el -a $antennaPick -d $el_command";
  print $command."\n";
  `el -a $antennaPick -d $el_command`;
  sleep(2);
  `antennaWait -a $antennaPick -e $antennawaitarcsec`;
  read_power($el_command);
}

sub read_power {#read total power
    my $elcmd = shift(@_);
    $pi = 3.14159265358979;
    for($i=0;$i<10;$i++){
      $index = 0;
      foreach $a (@antennalist) {
	if ($opt_syncdet) {
	      $powers = `value -a $a -v syncdet2_channels_v2`;
	      @list = split(' ',$powers);
	      $tot = $list[0];
	      $tot2 = $list[1];
	} else {
	      $totpowers = `value -a $a -v cont_det_muwatt_v2`;
	      @totpowerslist=split(' ',$totpowers);
	      $tot = $totpowerslist[0];
	      $tot2 = $totpowerslist[1];
	}
	$el = `value -a $a -v actual_el_deg`;
        $airmass = 1.0/cos((90.0-$el)*$pi/180.0);
#       $xnpts[$a] += 1;
#	$sumx[$a] += $airmass;
#	$sumx2[$a] += $airmass*$airmass;
#	$sumy[$a] += $tot;
#	$sumy2[$a] += $tot*$tot;
#	$sumxy[$a] += $tot*$airmass;
#	$sumyhf[$a] += $tot2;
#	$sumy2hf[$a] += $tot2*$tot2;
#	$sumxyhf[$a] += $tot2*$airmass;
	printf "%6.3f %8.5f %8.5f %8.5f\n",$el, $tot, $tot2, $airmass;
	printf { $fileHandles[$index] } "%6.3f %8.5f %8.5f %8.5f\n",$el, $tot, $tot2, $airmass;
	$index++;
      }
      sleep 1;
#      if ($elcmd == 16.60) {
#	  $slope = ( $xnpts[$a]*$sumxy[$a] - $sumx[$a]*$sumy[$a] ) / ( $xnpts[$a]*$sumx2[$a] - $sumx[$a]*$sumx[$a] );
#	  $intercept = ( $sumy[$a]*$sumx2[$a] - $sumx[$a]*$sumxy[$a] ) / ( $xnpts[$a]*$sumx2[$a] - $sumx[$a]*$sumx[$a] );
#	  $slope2 = ( $xnpts[$a]*$sumxyhf[$a] - $sumx[$a]*$sumyhf[$a] ) / ( $xnpts[$a]*$sumx2[$a] - $sumx[$a]*$sumx[$a] );
#	  $intercept2 = ( $sumyhf[$a]*$sumx2[$a] - $sumx[$a]*$sumxyhf[$a] ) / ( $xnpts[$a]*$sumx2[$a] - $sumx[$a]*$sumx[$a] );
#	  printf "antenna %d: tau (low-freq) = %.3f    (high-freq) = %.3f\n", $a, 
#	    $slope, $slope2;
#      }
    }
}

