#!/bin/tcsh -vf
set list = ""  # list of antennas
set alist = "" # list of antennas prepended with -a, or blank if using project
set args = $#argv
set ctr = 1
set loop = 0
foreach i ( $argv )
  set loop = `expr $loop + 1`
  if (`expr $loop == $ctr`) then
    if (`expr $i == '-h'` || `expr $i == '--help'`) then
      goto usage
    endif
    if (`expr $i == '-a'` || `expr $i == '--antenna'`) then
      if (`expr $ctr != $args`) then
        set ctr = `expr $ctr + 1`
        set list = $argv[$ctr]
        set alist = "-a $list"
        echo will use antenna argument = $alist
      else
        echo You must supply a list of antennas after -a
        goto usage
      endif
    endif
  endif
  set ctr = `expr $ctr + 1`
  endif
end

echo `date -u +"%a %b %d %X %Y"` '('$USER'):' $0 $argv >> /rootfs/logs/SMAshLog

optical $alist

wait
azelstarTilt $alist -z 270 -d up -b -w 5 -n 1
wait
azelstarTilt $alist -z 280 -d down -b -w 5 -n 1
wait
azelstarTilt $alist -z 290 -d up -b -w 5 -n 1
wait
azelstarTilt $alist -z 300 -d down -b -w 5 -n 1
wait
azelstarTilt $alist -z 310 -d up -b -w 5 -n 1
wait
azelstarTilt $alist -z 320 -d down -b -w 5 -n 1
wait
azelstarTilt $alist -z 330 -d up -b -w 5 -n 1
wait
azelstarTilt $alist -z 340 -d down -b -w 5 -n 1
wait
azelstarTilt $alist -z 350 -d up -b -w 5 -n 1
wait
azelstarTilt $alist -z 0 -d down -b -w 5 -n 1
wait
azelstarTilt $alist -z 10 -d up -b -w 5 -n 1
wait
azelstarTilt $alist -z 20 -d down -b -w 5 -n 1
wait
azelstarTilt $alist -z 30 -d up -b -w 5 -n 1
wait
azelstarTilt $alist -z 40 -d down -b -w 5 -n 1
wait
azelstarTilt $alist -z 50 -d up -b -w 5 -n 1
wait
azelstarTilt $alist -z 60 -d down -b -w 5 -n 1
wait
azelstarTilt $alist -z 70 -d up -b -w 5 -n 1
wait
azelstarTilt $alist -z 80 -d down -b -w 5 -n 1
wait
azelstarTilt $alist -z 90 -d up -b -w 5 -n 1
wait
azelstarTilt $alist -z 100 -d down -b -w 5 -n 1
wait
azelstarTilt $alist -z 110 -d up -b -w 5 -n 1
wait
azelstarTilt $alist -z 120 -d down -b -w 5 -n 1
wait
azelstarTilt $alist -z 130 -d up -b -w 5 -n 1
wait
azelstarTilt $alist -z 140 -d down -b -w 5 -n 1
wait
azelstarTilt $alist -z 150 -d up -b -w 5 -n 1
wait
azelstarTilt $alist -z 160 -d down -b -w 5 -n 1
wait
azelstarTilt $alist -z 170 -d up -b -w 5 -n 1
wait
azelstarTilt $alist -z 180 -d down -b -w 5 -n 1
wait
azelstarTilt $alist -z 190 -d up -b -w 5 -n 1
wait
azelstarTilt $alist -z 200 -d down -b -w 5 -n 1
wait
azelstarTilt $alist -z 210 -d up -b -w 5 -n 1
wait
azelstarTilt $alist -z 220 -d down -b -w 5 -n 1
wait
azelstarTilt $alist -z 230 -d up -b -w 5 -n 1
wait
azelstarTilt $alist -z 240 -d down -b -w 5 -n 1
wait
azelstarTilt $alist -z 250 -d up -b -w 5 -n 1
wait
azelstarTilt $alist -z 260 -d down -b -w 5 -n 1
wait
azelstarTilt $alist -z 270 -d up -b -w 5 -n 1
wait
radio $alist
wait

exit 0

usage:
  echo "Usage: $0 [-a <antennaList: comma-delimited>]"
  exit 0
