/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHART_H_RPCGEN
#define	_CHART_H_RPCGEN

#include <rpc/rpc.h>

struct chartCommand {
	short command;
	short integtime;
	short antennaID;
};
typedef struct chartCommand chartCommand;
#define	SUCCESS 1
#define	FAILURE 0
#define	QUIT 0
#define	AZSCAN 1
#define	ELSCAN 2
#define	SAVEON 3
#define	SAVEOFF 4
#define	CHOP 5
#define	TOTALP 6
#define	INTEG 7

#define	CHARTCOMMANDPROG	0x20000012
#define	CHARTCOMMANDVERS	1
#define	CHARTCOMMAND	1
extern  int * chartcommand_1();
extern int chartcommandprog_1_freeresult();

/* the xdr functions */
extern bool_t xdr_chartCommand();

#endif /* !_CHART_H_RPCGEN */
